name: 'Irssi Problem Matcher'
author: 'The Irssi team'
description: 'Annotate PRs with compiler warnings from Github actions output'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'check-circle'
  color: 'green'
